sonar.projectKey=asadullah-rind-mern-10pshine
sonar.projectName=Asadullah Rind MERN 10Pearls Shine

sonar.sources=frontend/src
sonar.tests=frontend/src/test

sonar.test.inclusions=frontend/src/test/**/*.test.jsx

sonar.exclusions=frontend/node_modules/**,frontend/coverage/**,frontend/dist/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info